# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - override /hydra/launcher: submitit_slurm
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: random

optimized_metric: "val_loss"

hydra:
  job: 
    name: evaluate
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: learning_rate
    n_trials: 4
    n_jobs: 4

    search_space:
      model.kwargs.learning_rate: 
        type: float 
        low: 0.001
        high: 0.4
        log: true
  launcher: 
    gres: gpu:1080_ti:1
    cpus_per_task: 4

    nodes: 1