target: awesome_ssl.models.eval_byol.BYOL_Eval
kwargs: 
  train_dir: /mnt/nfs/home/yunxingl/self-supervised-learning/outputs/2021-11-11/21-47-12
  weight_file: epoch_999.ckpt
  representation_size: 2048
  num_targets: 10
  learning_rate: 0.01
