target: awesome_ssl.models.byol.BYOL 
kwargs: 
  encoder_params: 
    target: awesome_ssl.models.trunk_models.resnets.resnet50
  projector_params: 
    target: awesome_ssl.models.projection_heads.MLP.MLP
    kwargs: 
      input_dim: 2048
      hidden_dim: 4096
      output_dim: 256
  predictor_params: 
    target: awesome_ssl.models.projection_heads.MLP.MLP
    kwargs: 
      input_dim: 256
      hidden_dim: 4096
      output_dim: 256
  tau: 4.0e-3
  accumulate_n_batch: 1
  transform_1: 
  - target: kornia.augmentation.CenterCrop
    kwargs: 
      size: 224
  - target: kornia.augmentation.RandomHorizontalFlip
  - target: kornia.augmentation.ColorJitter
  - target: kornia.augmentation.RandomGaussianBlur
    args: 
    - [19, 19] #kernel size
    - [1.0, 1.0] #sigma
  - target: kornia.augmentation.RandomSolarize
  transform_2: 
  - target: kornia.augmentation.CenterCrop
    kwargs: 
      size: 224
  - target: kornia.augmentation.RandomHorizontalFlip
  - target: kornia.augmentation.ColorJitter
  - target: kornia.augmentation.RandomGaussianBlur
    args: 
    - [19, 19] 
    - [1.0, 1.0] 
  - target: kornia.augmentation.RandomSolarize
  loss_module: 
    target: torch.nn.MSELoss
  optimizer_params: 
    target: torch.optim.SGD
    kwargs: 
      lr: 1.0e-3
      momentum: 0.9

