target: awesome_ssl.models.simclr.SimCLR 
kwargs: 
  encoder_params: 
    target: awesome_ssl.models.trunk_models.resnets.resnet50
  projector_params: 
    target: awesome_ssl.models.projection_heads.MLP.MLP
    kwargs: 
      input_dim: 2048
      hidden_dim: 4096
      output_dim: 128
  accumulate_n_batch: 1
  optimizer_params: 
    target: torch.optim.Adam
    kwargs: 
      lr: 1.0e-3
  eval_interval: 50
  linear_evaluate_config: 
    target: torch.nn.Linear
    kwargs: 
      in_features: 2048  # in features
      out_features: 10 # out features
  temperature: 1