wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "byol-linear-evaluate"
  name: debug
  save_dir: "."
  offline: False # set True to store all logs only locally
  # entity: ""  # set to name of your wandb team
  log_model: False
  prefix: ""
  job_type: "train"
  group: debug
  tags: []