model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_top_k: -1
  every_n_epochs: 20
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False
  save_on_train_epoch_end: True