model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_top_k: -1 # save k best models (determined by above metric)
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False
  every_n_epochs: 50 # change this according to # of epoch