model_checkpoint:
  _target_: awesome_ssl.callbacks.custom_checkpoint.CustomCheckpoint
  checkpoint_freq: 
  - [0, 9, 1]
  - [10, 49, 10]
  - [50, 1000, 50]
  save_top_k: -1
  every_n_epochs: 20
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False
  save_on_train_epoch_end: True