# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - model: byol.yaml
  - train_dataset: imagenet_byol.yaml
  - val_dataset: imagenet_val.yaml
  - trainer: default.yaml

batch_size: 50
