# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - model: byol.yaml
  - callbacks: pretrain_callbacks.yaml
  - train_dataset: imagenette.yaml
  - val_dataset: imagenette_val.yaml
  - trainer: default.yaml
  - logger: wandb_pretrain.yaml
  - sweep_configs: null
  - experiment: null


batch_size: 50
