# @package _global_
defaults: 
  - _self_
  - model: byol.yaml
  - callbacks: pretrain_callbacks.yaml
  - train_dataset: imagenette_byol.yaml
  - val_dataset: imagenette_val.yaml
  - trainer: debug_cpu.yaml
  - experiment: null
  - logger: wandb_pretrain.yaml

batch_size: 50